### ISSUE TITLE
你自己的API KEY不用拿掉嗎 ?

### ISSUE THREAD

**Issue by Dannyisadog** [chen0401/baiduLBS#1]

**Comment by chen0401** [comment]
需要更换成你自己的key，使用语音播报功能的话，还需要更换语音播报的key（MainAcitvity.java 78行）

**Comment by shangjingxie** [comment]
问下呢，你这个语音播报的TTS_APP_ID 是在哪里申请的，麻烦说具体点，我这找不到申请入口。
